In [1]:
import numpy as np

X = np.load('blood1X.npz')['X']

print(X)

[[0.2219921  0.28967193 0.12321366 ... 0.7465785  0.695997   0.73667264]
 [0.3309956  0.2712836  0.23891939 ... 0.74616057 0.79765964 0.788809  ]
 [0.30119124 0.33927497 0.2615666  ... 0.80447024 0.8753269  0.74814475]
 ...
 [0.24136552 0.3235496  0.3104295  ... 0.8309854  0.8573978  0.7491626 ]
 [0.30186263 0.28903267 0.2905033  ... 0.8167344  0.8695807  0.84649307]
 [0.16980827 0.28453425 0.27663615 ... 0.80469066 0.80659014 0.87913   ]]
